---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo
stringData:
  url: {{ include "lunchables.mongo-url" . | quote }}
  database: {{ include "lunchables.mongo-database" . | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio
stringData:
  endpoint: {{ include "lunchables.minio-endpoint" . | quote }}
  username: {{ include "lunchables.minio-username" . | quote }}
  password: {{ include "lunchables.minio-password" . | quote }}
  bucket: {{ .Values.minio.bucketName | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.dockerRegistry.domain .Values.dockerRegistry.username .Values.dockerRegistry.password .Values.dockerRegistry.email (printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kube
stringData:
  release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  mem_quota: {{ .Values.pipelineResources.mem | quote }}
  cpu_quota: {{ .Values.pipelineResources.cpu | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-elastic
stringData:
  endpoint: {{ include "lunchables.elasticsearch-endpoint" . | quote }}
