apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: {{ image_pull_secret }}
  containers:
    - name: phase0
      image: {{ self_image }}
      imagePullPolicy: {{ image_pull_policy }}
      securityContext:
        privileged: true
      command:
        - "bash"
        - "-c"
        - |
          BASE="/tmp/gh-rhelmot"
          rm -rf $BASE
          mkdir -p $BASE $BASE/results $BASE/patches $BASE/logs
          #ln -s /shared/greenhouse/full/cache $BASE/cache
          ln -s "/shared/{{ target.filename }}" $BASE/input.zip
          echo "{{ target.brand }}" "{{ target.basename }}" input.zip >$BASE/full.list
          /gh/entrypoint.sh $BASE $BASE/full.list 0
          echo 'Greenhouse Logs:'
          cat $BASE/logs/*
          aws --endpoint-url "{{ greenhouse_result.endpoint }}" s3 cp $BASE/results/* "{{ greenhouse_result }}"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ bucket_secret }}
              key: username
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ bucket_secret }}
              key: password
      resources:
        requests:
          cpu: 1
          memory: 8Gi
        limits:
          cpu: 4
          memory: 32Gi
      volumeMounts:
        - name: rwx
          mountPath: "/shared"
        - name: fakedev
          mountPath: "/host/dev"
  volumes:
    - name: rwx
      persistentVolumeClaim:
        claimName: {{ rwx_pvc }}
    - name: fakedev
      hostPath:
        path: /dev
        type: ""
