name: Lunchables Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy 
    runs-on: lunchables-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.RHELMOT_SSH_KEY }}
      - name: Set up Docker Context
        run: docker context create mine
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: mine
      - name: Login to Shellphish Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.shellphish.net
          username: shellphish
          password: ${{ secrets.SHELLPHISH_DOCKER_PASSWORD }}
      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0
      - name: Helm Deps
        run: "sudo apt-get update && sudo apt-get install -y unzip"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3
      - name: Build and Push Images
        run: ./build-images-private.sh
      - name: Set Secrets
        env:
          SHELLPHISH_DOCKER_PASSWORD: ${{ secrets.SHELLPHISH_DOCKER_PASSWORD}}
          RHELMOT_MINIO_PASSWORD: ${{ secrets.RHELMOT_MINIO_PASSWORD }}
          RHELMOT_SEFCOM_KUBE_CONFIG: ${{ secrets.RHELMOT_SEFCOM_KUBE_CONFIG }}
        run: |
          cat >deploy/secrets.yaml <<EOF
          dockerRegistry:
            password: "$SHELLPHISH_DOCKER_PASSWORD"
          minio:
            existingPassword: "$RHELMOT_MINIO_PASSWORD"
          EOF
          mkdir -p ~/.kube
          echo "$RHELMOT_SEFCOM_KUBE_CONFIG" >~/.kube/config
      - name: Upgrade Deployment
        run: ./deploy/deploy.sh
